services:
  openig:
    # image: openidentityplatform/openig:latest
    image: openig-test:latest
    build: ./openig
    container_name: openig
    volumes:
      - ./openig-config:/usr/local/openig-config:ro
    # environment:
    #   CATALINA_OPTS: -Dopenig.base=/usr/local/openig-config -Doauth.client_id=<client_id> -Doauth.client_secret=<client_secret> -DallowedEmails=ivan.ivanov@yandex.ru -Dendpoint.app=http://app:8080      
    env_file:
        - dev.env        
    ports:
      - "8080:8080"
      - "5005:5005"

  app:
    image: caddy
    volumes:
      - ./app/src:/usr/share/caddy/app:ro
    ports:
      - "8082:80"